### ISSUE TITLE
Submitting upstream?

### ISSUE THREAD

**Issue by technomancy** [SteffenBauer/elixir-gtksourceview#3]
Is there any reason not to merge this into upstream? It seems to be quite stable and do a good job at highlighting. I was looking at using gedit with Elixir and I almost didn't find this repository, so I initially assumed it wouldn't work.

It looks like new languages can be added here: https://gitlab.gnome.org/GNOME/gtksourceview/-/issues/1

**Comment by SteffenBauer** [comment]
Actually there is no special reason why it isn't included in the gtksourceview language specs.

I started the project when Elixir was just gaining first traction. A link was included for a long time on the Elixir homepage to this repository, so I thought this should be sufficient for people to find syntax highlighting for gedit.

My interests shifted away from Elixir in the last years, so I look into this repository only occasionally.

As I don't have an account on gnome gitlab yet and don't want to open an account just for this single task, it would be the most easiest if you or somebody else could open there an issue asking for the elixir.lang be included in `/data/language-specs` ? @technomancy

**Comment by technomancy** [comment]
Sure; I don't mind submitting upstream as long as you're OK with it. Thanks for confirming.

**Comment by technomancy** [comment]
I've opened a draft here but I want to see if more keywords need to be added which are new since 1.10.x: https://gitlab.gnome.org/GNOME/gtksourceview/-/merge_requests/342

**Comment by SteffenBauer** [comment]
Thanks for opening the draft. I will also look this afternoon into updating the file.

**Comment by SteffenBauer** [comment]
Went the last hours through the documentation for Elixir kernel and ExUnit, updated the file with keywords. Please report if anything is missing.
Thanks again for looking into this matter and starting the pull request at gtksourceview.

**Comment by technomancy** [comment]
Cool; thanks. I've updated the upstream patch; hopefully that can be applied soon.

**Comment by SteffenBauer** [comment]
Seems to have been merged to upstream 👍 so closing this issue.
